services:
  chrome_ext_thon:
    image: jpyles0524/gemini-rec-search-api:042bd339f3afb70e7cc39e1e9910a81a215db2f4
    env_file: .env
    volumes:
      - "$PWD/api:/project/api"
    ports:
      - 8000:8000
